# Generated by Django 5.2.7 on 2025-12-18 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_item_custom_category_remove_item_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_imported',
            field=models.BooleanField(default=False),
        ),
    ]
